[package]
name = "test-ecdsa"
version = "0.1.0"
edition = "2021"

[dependencies]
p256 = { version = "0.11", features = ["ecdsa", "sha256"] }
sha2 = "0.10"
signature = "1.6"
rand_core = { version = "0.6", features = ["std"] }